# Created by Jekyll Writer
title: Your awesome title
author: Jekyll Writer
description: 这是Fantome的个人学习博客
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: jekyllwriter
github_username: jekyllwriter
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''
